### ISSUE TITLE
Error on test_vlopt_rivanna.sh - NetworkX version?

### ISSUE THREAD

**Issue by bryanleroylewis** [NSSAC/variant-list-optimizer#1]
@parantapa installed the vlopt and was trying to run the test script, got an error.  Does it look familiar?  Seems odd, might be mismatch NetworkX versions or something?  I'm running this from a terminal tab in the "portal / ood"  can try other ways if this does't make sense... 

Including full echo for good measure... 
```
bash-4.4$./test_vlopt_rivanna.sh 
############ export GRB_LICENSE_FILE="/apps/software/vendor/gurobi/11.0.0/gurobi.lic"
############ DATA_FILE="/project/nssac_covid19/COVID-19_commons/products/external_data_collection/variants/outbreak_info_variants_states_long.csv"
############ START_DATE="2021-01-01"
############ END_DATE="2024-10-25"
############ FIPS_LIST="42,54,51,10,24"
############ TEMPORAL_IMPORTANCE_DECAY="0.1"
############ DISTANCE_PENALTY="10.0"
############ LIST_SIZE=20
############ VALIDATED_DATA_FILE="/scratch/$USER/obs-count.parquet"
############ UNWEIGHTED_VARIANT_GRAPH_FILE="/scratch/$USER/unweighted_variant-graph.json"
############ VARIANT_GRAPH_FILE="/scratch/$USER/variant-graph.json"
############ OPT_VARIANT_LIST_GREEDY="/scratch/$USER/opt-variant-list-greedy.json"
############ OPT_VARIANT_LIST_BEAM_SEARCH="/scratch/$USER/opt-variant-list-beam-search.json"
############ OPT_VARIANT_LIST_GUROBI="/scratch/$USER/opt-variant-list-gurobi.json"
############ vlopt make-graph validate-input --input "$DATA_FILE" --output "$VALIDATED_DATA_FILE"
############ vlopt make-graph make-variant-graph --input "$VALIDATED_DATA_FILE" --output "$UNWEIGHTED_VARIANT_GRAPH_FILE" --fips-list "$FIPS_LIST" --start-date "$START_DATE" --end-date "$END_DATE"
# rows in input data: 1105802
# rows after fips filtering: 87345
# rows after start date filtering: 84064
# rows after end date filtering: 84064
# observed variants: 2019
# nodes in variant graph: 2130
# edges in variant graph: 2129
Traceback (most recent call last):
  File "/home/bl4zc/.local/bin/vlopt", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/apps/software/standard/core/jupyterlab/3.6.3-py3.11/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/apps/software/standard/core/jupyterlab/3.6.3-py3.11/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/apps/software/standard/core/jupyterlab/3.6.3-py3.11/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/apps/software/standard/core/jupyterlab/3.6.3-py3.11/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/apps/software/standard/core/jupyterlab/3.6.3-py3.11/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/apps/software/standard/core/jupyterlab/3.6.3-py3.11/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bl4zc/.local/lib/python3.11/site-packages/variant_list_optimizer/make_graph.py", line 150, in make_variant_graph
    graph_json = nx.node_link_data(G, edges="edges")  # type: ignore
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: node_link_data() got an unexpected keyword argument 'edges'
```

**Comment by parantapa** [comment]
Hey, @bryanleroylewis you have a older version of networkx installed.
You can update the version using "pip install -U networkx".
Can you let me know if that works?

**Comment by bryanleroylewis** [comment]
@parantapa   that worked!!! Hooray!

but.... 

`gurobipy.GurobiError: Unable to open Gurobi license file '/apps/software/vendor/gurobi/11.0.0/gurobi.lic'`

Getting permission denied from command line... guessing i need to be in the gurobi users group

**Comment by parantapa** [comment]
You probably don't have access to the file.
Will discuss with you offline.

Since the neworkx issue is resolved, I am closing this here.
